TMNT/Models/ViewModels/VolumetricViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TMNT.Models.ViewModels {
    public class VolumetricIndexViewModel {

        [Display(Name = "Volumetric ID")]
        public int VolumetricId { get; set; }
        [Display(Name = "Device Code")]
        public string DeviceCode { get; set; }
        public Department Department { get; set; }
        [Display(Name = "Balance Used")]
        public Device BalanceUsed { get; set; }
        [Display(Name = "Is Verified")]
        public bool IsVerified { get; set; }
        [DataType(DataType.Date), Display(Name = "Last Verified")]
        public DateTime LastVerified { get; set; }
        [Display(Name = "Last Verified By")]
        public string LastVerifiedBy { get; set; }
        
        public List<DeviceVerification> DeviceVerifications { get; set; }
    }

    public class VolumetricVerificationViewModel {
        [Required(ErrorMessage = "Balance ID is Required"), Display(Name = "Balance ID")]
        public int VolumetricId { get; set; }
        [Required(ErrorMessage = "Device Code is Required"), Display(Name = "Device Code")]
        public string DeviceCode { get; set; }
        public Location Location { get; set; }
        [Display(Name = "Weight One")]
        public double? WeightOne { get; set; }
        [Display(Name = "Weight Two")]
        public double? WeightTwo { get; set; }
        [Display(Name = "Weight Three")]
        public double? WeightThree { get; set; }
        [DataType(DataType.MultilineText)]
        public string Comments { get; set; }
        [Display(Name = "Verification Standing")]
        public bool IsVerified { get; set; }
        [Display(Name = "Last Verified"), DataType(DataType.Date)]
        public DateTime? LastVerified { get; set; }
        public string Status { get; set; }//in good standing, getting repaired etc
        [Display(Name = "Last Verified By")]
        public string LastVerifiedBy { get; set; }//full name
        public Department Department { get; set; }
        [Display(Name = "Last Verified By")]
        public string VerifiedBy { get; set; }


        public int NumberOfTestsToVerify { get; set; }
        public string WeightLimitOne { get; set; }
        public string WeightLimitTwo { get; set; }
        public string WeightLimitThree { get; set; }

        //properties to populate view
        public List<string> LocationNames { get; set; }
        public string CurrentLocation { get; set; }
        public int NumberOfDecimals { get; set; }

        //for details
        public List<DeviceVerification> DeviceVerifications { get; set; }
    }

    public class VolumetricDetailsViewModel {

    }

    public class VolumetricCreateViewModel {
        public int VolumetricDeviceId { get; set; }
        public string DeviceCode { get; set; }
        public string DepartmentName { get; set; }
        [Required(ErrorMessage = "Sub Department is Required"), Display(Name = "Sub Department")]
        public string SubDepartmentName { get; set; }
        [Required(ErrorMessage = "Location Name is Required"), Display(Name = "Location Name")]
        public string LocationName { get; set; }
        public string VolumetricType { get; set; }
        public string Categorization { get; set; }
        public string Frequency { get; set; }
        public string Volume { get; set; }
        public string AcceptanceCriteria { get; set; }

        //properties to help populate the view
        public List<string> LocationNames { get; set; }
        public List<Department> Departments { get; set; }
        public List<Department> SubDepartments { get; set; }
        public List<string> DeviceTypes = new List<string>() { "Pipette - Adjustable", "Pipette - Fixed", "Dispenser - Adjustable", "Pipette - Fixed", "Syringe", "Class A Labware", "Class B Labware", "Tubes", "Scoops" };
        public List<string> Categorizations = new List<string>() { "Critical", "Non-Critical" };
        public List<string> Frequencies = new List<string>() { "Daily", "Weekly", "Monthly", "Annually" };
        public List<string> AcceptanceCriterias = new List<string>() { "2%", "5%", "10%" };
    }
}

TMNT/Controllers/VolumetricController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TMNT.Filters;
using TMNT.Models;
using TMNT.Models.Enums;
using TMNT.Models.Repository;
using TMNT.Models.ViewModels;
using TMNT.Utils;

namespace TMNT.Controllers {
    [Authorize]
    [PasswordChange]
    public class VolumetricController : Controller {

        private UnitOfWork _uow;
        public VolumetricController()
            : this(new UnitOfWork()) {
        }

        public VolumetricController(UnitOfWork uow) {
            this._uow = uow;
        }

        // GET: Volumetric
        [Route("Volumetrics")]
        public ActionResult Index() {
            var department = _uow.GetUserDepartment();

            var volumetrics = _uow.VolumetricDeviceRepository.Get().Where(item => item.Department.Equals(department));
            var viewModels = new List<VolumetricIndexViewModel>();

            foreach (var item in volumetrics) {
                viewModels.Add(new VolumetricIndexViewModel() {
                    VolumetricId = item.DeviceId,
                    DeviceCode = item.DeviceCode,
                    IsVerified = item.IsVerified,
                    Department = item.Department,
                    LastVerifiedBy = item.DeviceVerifications//last verified by
                                .Where(x => x.Device.Equals(item))
                                .Count() == 0 ?
                                    null :
                                    item.DeviceVerifications
                                        .Where(x => x.Device.Equals(item))
                                        .OrderBy(x => x.VerifiedOn)
                                        .Select(x => x.User.UserName)
                                        .First()
                });
            }
            return View(viewModels);
        }

        // GET: Volumetric/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = _uow.VolumetricDeviceRepository.Get(id);
            if (device == null) {
                return HttpNotFound();
            }
            return View(device);
        }

        // GET: Volumetric/Create
        [Route("Volumetric/Create")]
        public ActionResult Create() {
            return View(SetCreateVolumetric(new VolumetricCreateViewModel()));
        }

        // POST: Volumetric/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Volumetric/Create")]
        public ActionResult Create([Bind(Include = "DeviceId,DeviceCode,IsVerified,DeviceType,Status")] Device device) {
            if (ModelState.IsValid) {
                _uow.VolumetricDeviceRepository.Create(device);
                return RedirectToAction("Index");
            }
            return View(device);
        }

        [Route("Volumetric/Verification/{id?}")]
        public ActionResult Verification(int? id) {
            //sending all Locations to the view
            var locations = _uow.LocationRepository.Get().Select(name => name.LocationName).ToList();
            var balance = _uow.VolumetricDeviceRepository.Get(id);

            var device = new VolumetricVerificationViewModel() {
                VolumetricId = balance.DeviceId,
                Location = balance.Department.Location,
                DeviceCode = balance.DeviceCode,
                CurrentLocation = balance.Department.Location.LocationName,
                LocationNames = locations,
                NumberOfTestsToVerify = balance.NumberOfTestsToVerify,
                WeightLimitOne = balance.AmountLimitOne + " g",
                WeightLimitTwo = balance.AmountLimitTwo + " g ",
                WeightLimitThree = balance.AmountLimitThree == null ? null : balance.AmountLimitThree + " g",
                NumberOfDecimals = balance.NumberOfDecimals
            };
            return View(device);
        }

        // GET: Volumetric/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = _uow.VolumetricDeviceRepository.Get(id);
            if (device == null) {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Volumetric/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DeviceId,DeviceCode,IsVerified,DeviceType,Status")] Device device) {
            var result = CheckModelState.Invalid;
            if (ModelState.IsValid) {
                _uow.VolumetricDeviceRepository.Update(device);
                result = _uow.Commit();

                //TODO cases
                switch (result) {
                    case CheckModelState.UpdateError:
                        break;
                    case CheckModelState.ConcurrencyError:
                        break;
                    case CheckModelState.Invalid:
                        break;
                    case CheckModelState.Disposed:
                        break;
                    case CheckModelState.Valid:
                        return RedirectToAction("Index");
                    case CheckModelState.DataError:
                        break;
                    case CheckModelState.Error:
                        break;
                    default:
                        break;
                }
            }
            return View(device);
        }

        // GET: Volumetric/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var device = _uow.VolumetricDeviceRepository.Get(id);
            if (device == null) {
                return HttpNotFound();
            }
            _uow.VolumetricDeviceRepository.Delete(id);

            var result = _uow.Commit();

            return View(device);
        }

        // POST: Volumetric/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            _uow.VolumetricDeviceRepository.Delete(id);
            var result = _uow.Commit();

            return RedirectToAction("Index");
        }

        private VolumetricCreateViewModel SetCreateVolumetric(VolumetricCreateViewModel model) {
            var locations = _uow.LocationRepository.Get();
            var departments = _uow.DepartmentRepository.Get();

            model.LocationNames = locations.Select(item => item.LocationName).ToList();
            model.Departments = departments
                .Where(item => !item.DepartmentName.Equals("Quality Assurance"))
                .GroupBy(item => item.DepartmentName)
                .Select(item => item.First()).ToList();
            model.SubDepartments = departments
                .Where(item => !string.IsNullOrEmpty(item.SubDepartment) || !item.DepartmentName.Equals("Quality Assurance"))
                .ToList();

            return model;
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                _uow.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TMNT/Views/Volumetric/Delete.cshtml
@model TMNT.Models.Device

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVerified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVerified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TMNT/Views/Volumetric/Details.cshtml
@model TMNT.Models.Device

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVerified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVerified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DeviceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TMNT/Views/Volumetric/Edit.cshtml
@model TMNT.Models.Device

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DeviceId)

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsVerified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsVerified)
                    @Html.ValidationMessageFor(model => model.IsVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeviceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeviceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TMNT/Views/Volumetric/Index.cshtml
@model IEnumerable<TMNT.Models.ViewModels.VolumetricIndexViewModel>

@{
    ViewBag.Title = "Index";
}

@section AddToHead {
    <link href="../../Content/dataTables.min.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-lg-12">
        <h1>
            Volumetrics
        </h1>
        <ol class="breadcrumb no-border-radius">
            <li class="active">
                <i class="fa fa-dashboard"></i>@Html.ActionLink(" Dashboard", "Index", "Home") / <i class="fa fa-wrench"></i> Devices / <i class="fa fa-circle-o"></i> Volumetrics
            </li>
        </ol>
    </div>
</div>

<p>
    @Html.ActionLink("New Volumetric", "Create", "Volumetric", null, htmlAttributes: new { @class = "btn btn-default" })
</p>

<hr />

<table id="myTable" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Action</th>
            <th>@Html.DisplayNameFor(model => model.DeviceCode)</th>
            <th>@Html.DisplayNameFor(model => model.Department.DepartmentName)</th>
            <th>@Html.DisplayNameFor(model => model.IsVerified)</th>
            <th>Last Verified By</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.VolumetricId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.VolumetricId }) |
                    @Html.ActionLink("Archive", "Delete", new { id = item.VolumetricId })
                    @if (!@item.IsVerified) {
                        <text>|</text> @Html.ActionLink("Verify", "Verification", new { id = item.VolumetricId }, htmlAttributes: new { @class = "text-danger" })
                    }
                </td>
                <td>
                    @item.DeviceCode
                </td>
                <td>
                    @item.Department.DepartmentName
                </td>
                @if (!@item.IsVerified) {
                    <td class="text-danger">
                        Not Verified <span class="fa fa-times-circle"></span>
                    </td>
                } else {
                    <td class="text-success">
                        Verified <span class="fa fa-check-circle"></span>
                    </td>
                }
                @if (@item.LastVerifiedBy == null) {
                    <td>
                        N/A
                    </td>
                } else {
                    <td>
                        @item.LastVerifiedBy
                    </td>
                }
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Action</th>
            <th>@Html.DisplayNameFor(model => model.DeviceCode)</th>
            <th>@Html.DisplayNameFor(model => model.Department.DepartmentName)</th>
            <th>@Html.DisplayNameFor(model => model.IsVerified)</th>
            <th>Last Verified By</th>
        </tr>
    </tfoot>
</table>
@Scripts.Render("~/datatables")