TMNT/Models/MaxxamMadeStandard.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TMNT.Models {
    public class MaxxamMadeStandard {
        public MaxxamMadeStandard() {
            InventoryItems = new List<InventoryItem>();
        }
        [Key]
        public int MaxxamMadeStandardId { get; set; }
        public string MaxxamId { get; set; }
        public string IdCode { get; set; }
        public string MaxxamMadeStandardName { get; set; }
        public string SolventUsed { get; set; }
        public string SolventSupplierName { get; set; }
        public double Purity { get; set; }
        public string LastModifiedBy { get; set; }

        //foreign keys
        public virtual ICollection<InventoryItem> InventoryItems { get; set; }
    }
}

TMNT/Models/ViewModels/MaxxamMadeStandardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TMNT.Models.ViewModels {
    public class MaxxamMadeStandardViewModel {
        public int MaxxamMadeStandardId { get; set; }

        //stock standard properties
        [Display(Name = "ID Code")]
        public string IdCode { get; set; }
        [Display(Name = "Standard Name")]
        public string MaxxamMadeStandardName { get; set; }
        [Display(Name = "Date Opened")]
        public DateTime? DateOpened { get; set; }
        [Display(Name = "Created By")]
        public string CreatedBy { get; set; }
        [DataType(DataType.Date), Display(Name = "Date Last Modified")]
        public DateTime? DateModified { get; set; }
        [Display(Name = "Last Modified By")]
        public string LastModifiedBy { get; set; }
        [Display(Name = "Solvent Used"), DataType(DataType.MultilineText)]
        public string SolventUsed { get; set; }
        [Required, Display(Name = "Solvent Supplier")]
        public string SolventSupplierName { get; set; }
        [Display(Name = "Supplier")]
        public string SupplierName { get; set; }
        //[Required]
        public double Purity { get; set; }
        //public double LowAmountThreshHold { get; set; }
        [Display(Name = "Maxxam Id")]
        public string MaxxamId { get; set; }
        [Display(Name = "Expiry Date"), DataType(DataType.Date)]
        public DateTime? ExpiryDate { get; set; }

        //properties to help with views and have nothing to do with the db
        public bool IsExpired { get; set; }
        public bool IsOpened { get; set; }

        //inventory properties
        [Required, Display(Name = "Storage Req's")]
        public string StorageRequirements { get; set; }
        [Display(Name = "SDS Notes"), DataType(DataType.MultilineText)]
        public string MSDSNotes { get; set; }
        [Display(Name = "SDS Expiry Date"), DataType(DataType.Date)]
        public DateTime MSDSExpiryDate { get; set; }
        [Display(Name = "Catalogue Code")]
        public string CatalogueCode { get; set; }
        //[Display(Name = "Amount Remaining")]
        //public int Amount { get; set; }
        [Display(Name = "Case Number")]
        public int CaseNumber { get; set; }
        [Display(Name = "Used For"), DataType(DataType.MultilineText)]
        public string UsedFor { get; set; }
        [Display(Name = "SDS")]
        public MSDS MSDS { get; set; }
        [DataType(DataType.Date), Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }
        [Display(Name = "Certificate of Analysis")]
        public CertificateOfAnalysis CertificateOfAnalysis { get; set; }
        public Unit Unit { get; set; }
        public Department Department { get; set; }

        public List<CertificateOfAnalysis> AllCertificatesOfAnalysis { get; set; }
        public List<MSDS> AllMSDS { get; set; }
    }
}

TMNT/Controllers/MaxxamMadeStandardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TMNT.Filters;
using TMNT.Models;
using TMNT.Models.Repository;
using TMNT.Models.ViewModels;
using TMNT.Utils;

namespace TMNT.Controllers {
    [Authorize]
    [PasswordChange]
    public class MaxxamMadeStandardController : Controller {
        private ApplicationDbContext db = new ApplicationDbContext();

        private IRepository<MaxxamMadeStandard> repoStandard;
        public MaxxamMadeStandardController()
            : this(new MaxxamMadeStandardRepository(DbContextSingleton.Instance)) {
        }

        public MaxxamMadeStandardController(IRepository<MaxxamMadeStandard> repoStandard) {
            this.repoStandard = repoStandard;
        }

        // GET: MaxxamMadeStandards
        [Route("InHouseStandard")]
        public ActionResult Index() {
            var standards = repoStandard.Get();
            List<MaxxamMadeStandardViewModel> list = new List<MaxxamMadeStandardViewModel>();

            foreach (var item in standards) {
                list.Add(new MaxxamMadeStandardViewModel() {
                    MaxxamMadeStandardId = item.MaxxamMadeStandardId,
                    MaxxamId = item.MaxxamId,
                    MaxxamMadeStandardName = item.MaxxamMadeStandardName,
                    IdCode = item.IdCode,
                    LastModifiedBy = item.LastModifiedBy,
                    Purity = item.Purity,
                    SolventUsed = item.SolventUsed
                });
            }
            //iterating through the associated InventoryItem and retrieving the appropriate data
            //this is faster than LINQ
            int counter = 0;
            foreach (var standard in standards) {
                foreach (var invItem in standard.InventoryItems) {
                    if (standard.MaxxamMadeStandardId == invItem.MaxxamMadeStandard.MaxxamMadeStandardId) {
                        list[counter].CertificateOfAnalysis = invItem.CertificatesOfAnalysis.Where(x => x.InventoryItem.InventoryItemId == invItem.InventoryItemId).First();
                        list[counter].MSDS = invItem.MSDS.Where(x => x.InventoryItem.InventoryItemId == invItem.InventoryItemId).First();
                        list[counter].UsedFor = invItem.UsedFor;
                        //list[counter].Unit = invItem.Unit;
                        list[counter].CatalogueCode = invItem.CatalogueCode;
                        list[counter].ExpiryDate = invItem.ExpiryDate;
                        list[counter].IsExpired = invItem.ExpiryDate.Value.Date >= DateTime.Today;
                        list[counter].DateOpened = invItem.DateOpened;
                        list[counter].IsOpened = invItem.DateOpened != null;
                        list[counter].SupplierName = invItem.SupplierName;
                        list[counter].DateCreated = invItem.DateCreated;
                        list[counter].CreatedBy = invItem.CreatedBy;
                        list[counter].DateModified = invItem.DateModified;
                    }
                }
                counter++;
            }
            return View(list);
        }

        // GET: MaxxamMadeStandards/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaxxamMadeStandard maxxamMadeStandard = db.MaxxamMadeStandard.Find(id);
            if (maxxamMadeStandard == null) {
                return HttpNotFound();
            }
            return View(maxxamMadeStandard);
        }

        // GET: MaxxamMadeStandards/Create
        [Route("InHouseStandard/Create")]
        public ActionResult Create() {
            return View();
        }

        // POST: MaxxamMadeStandards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("InHouseStandard/Create")]
        public ActionResult Create([Bind(Include = "MaxxamMadeStandardId,LotNumber,IdCode,MaxxamMadeStandardName,SolventUsed,SolventSupplierName,Purity,LastModifiedBy")] MaxxamMadeStandard maxxamMadeStandard) {
            if (ModelState.IsValid) {
                db.MaxxamMadeStandard.Add(maxxamMadeStandard);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(maxxamMadeStandard);
        }

        // GET: MaxxamMadeStandards/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaxxamMadeStandard maxxamMadeStandard = db.MaxxamMadeStandard.Find(id);
            if (maxxamMadeStandard == null) {
                return HttpNotFound();
            }
            return View(maxxamMadeStandard);
        }

        // POST: MaxxamMadeStandards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaxxamMadeStandardId,LotNumber,IdCode,MaxxamMadeStandardName,SolventUsed,SolventSupplierName,Purity,LastModifiedBy")] MaxxamMadeStandard maxxamMadeStandard) {
            if (ModelState.IsValid) {
                db.Entry(maxxamMadeStandard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(maxxamMadeStandard);
        }

        // GET: MaxxamMadeStandards/Delete/5
        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MaxxamMadeStandard maxxamMadeStandard = db.MaxxamMadeStandard.Find(id);
            if (maxxamMadeStandard == null) {
                return HttpNotFound();
            }
            return View(maxxamMadeStandard);
        }

        // POST: MaxxamMadeStandards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            MaxxamMadeStandard maxxamMadeStandard = db.MaxxamMadeStandard.Find(id);
            db.MaxxamMadeStandard.Remove(maxxamMadeStandard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TMNT/Views/MaxxamMadeStandard/Create.cshtml
@model TMNT.Models.MaxxamMadeStandard

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MaxxamMadeStandard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaxxamId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxxamId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxxamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxxamMadeStandardName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxxamMadeStandardName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxxamMadeStandardName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SolventUsed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolventUsed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolventUsed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SolventSupplierName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolventSupplierName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolventSupplierName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TMNT/Views/MaxxamMadeStandard/Delete.cshtml
@model TMNT.Models.MaxxamMadeStandard

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MaxxamMadeStandard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LotNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LotNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxxamMadeStandardName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxxamMadeStandardName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SolventUsed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolventUsed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SolventSupplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolventSupplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedBy)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TMNT/Views/MaxxamMadeStandard/Details.cshtml
@model TMNT.Models.MaxxamMadeStandard

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MaxxamMadeStandard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LotNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LotNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxxamMadeStandardName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxxamMadeStandardName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SolventUsed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolventUsed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SolventSupplierName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SolventSupplierName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Purity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModifiedBy)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaxxamMadeStandardId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TMNT/Views/MaxxamMadeStandard/Edit.cshtml
@model TMNT.Models.MaxxamMadeStandard

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MaxxamMadeStandard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaxxamMadeStandardId)

        <div class="form-group">
            @Html.LabelFor(model => model.LotNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LotNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LotNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxxamMadeStandardName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxxamMadeStandardName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxxamMadeStandardName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SolventUsed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolventUsed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolventUsed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SolventSupplierName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SolventSupplierName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SolventSupplierName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Purity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Purity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModifiedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TMNT/Views/MaxxamMadeStandard/Index.cshtml
@model IEnumerable<TMNT.Models.ViewModels.MaxxamMadeStandardViewModel>

@{
    ViewBag.Title = "Index";
}

@section AddToHead {
    <link href="../../Content/dataTables.min.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            In-House Standards
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i>@Html.ActionLink(" Dashboard", "Index", "Home") / <i class="fa fa-flask"></i> In-House Standards
            </li>
        </ol>
    </div>
</div>

<p>
    @Html.ActionLink("New In-House Standard", "Create", "MaxxamMadeStandard", null, htmlAttributes: new { @class = "btn btn-default" })
</p>

<hr />

<table id="myTable" class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Action</th>
            <th>
                @Html.DisplayNameFor(model => model.MaxxamMadeStandardName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOpened)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxxamId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.MaxxamMadeStandardId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.MaxxamMadeStandardId }) |
                    <a href="#">Print Label</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxxamMadeStandardName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOpened)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxxamId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpiryDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>Action</th>
            <th>
                @Html.DisplayNameFor(model => model.MaxxamMadeStandardName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOpened)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxxamId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
        </tr>
    </tfoot>
</table>
@Scripts.Render("~/datatables")